src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceRepository::class)
 */
class Invoice
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\ManyToOne(targetEntity=Staff::class, inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $BilledStaffID;

    /**
     * @ORM\Column(type="date")
     */
    private $DateOfIssue;

    /**
     * @ORM\OneToMany(targetEntity=InvoiceItems::class, mappedBy="InvoiceID", orphanRemoval=true)
     */
    private $invoiceItems;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Paid;

    /**
     * @ORM\ManyToOne(targetEntity=Cases::class, inversedBy="invoices")
     */
    private $cases;

    public function __toString(): string
    {
        return $this->Name;
    }

    public function __construct()
    {
        $this->invoiceItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getBilledStaffID(): ?Staff
    {
        return $this->BilledStaffID;
    }

    public function setBilledStaffID(?Staff $BilledStaffID): self
    {
        $this->BilledStaffID = $BilledStaffID;

        return $this;
    }

    public function getDateOfIssue(): ?\DateTimeInterface
    {
        return $this->DateOfIssue;
    }

    public function setDateOfIssue(\DateTimeInterface $DateOfIssue): self
    {
        $this->DateOfIssue = $DateOfIssue;

        return $this;
    }

    /**
     * @return Collection|InvoiceItems[]
     */
    public function getInvoiceItems(): Collection
    {
        return $this->invoiceItems;
    }

    public function addInvoiceItem(InvoiceItems $invoiceItem): self
    {
        if (!$this->invoiceItems->contains($invoiceItem)) {
            $this->invoiceItems[] = $invoiceItem;
            $invoiceItem->setInvoiceID($this);
        }

        return $this;
    }

    public function removeInvoiceItem(InvoiceItems $invoiceItem): self
    {
        if ($this->invoiceItems->removeElement($invoiceItem)) {
            // set the owning side to null (unless already changed)
            if ($invoiceItem->getInvoiceID() === $this) {
                $invoiceItem->setInvoiceID(null);
            }
        }

        return $this;
    }

    public function getPaid(): ?bool
    {
        return $this->Paid;
    }

    public function setPaid(bool $Paid): self
    {
        $this->Paid = $Paid;

        return $this;
    }

    public function getCases(): ?Cases
    {
        return $this->cases;
    }

    public function setCases(?Cases $cases): self
    {
        $this->cases = $cases;

        return $this;
    }
}

src/Entity/InvoiceItems.php
<?php

namespace App\Entity;

use App\Repository\InvoiceItemsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceItemsRepository::class)
 */
class InvoiceItems
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Invoice::class, inversedBy="invoiceItems")
     * @ORM\JoinColumn(nullable=false)
     */
    private $InvoiceID;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $Rate;

    /**
     * @ORM\Column(type="float")
     */
    private $Adjusments;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoiceID(): ?Invoice
    {
        return $this->InvoiceID;
    }

    public function setInvoiceID(?Invoice $InvoiceID): self
    {
        $this->InvoiceID = $InvoiceID;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getRate(): ?float
    {
        return $this->Rate;
    }

    public function setRate(float $Rate): self
    {
        $this->Rate = $Rate;

        return $this;
    }

    public function getAdjusments(): ?float
    {
        return $this->Adjusments;
    }

    public function setAdjusments(float $Adjusments): self
    {
        $this->Adjusments = $Adjusments;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
}

src/Controller/InvoicesController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Entity\Cases;
use App\Entity\Client;
use App\Entity\InvoiceItems;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

use Knp\Snappy\Pdf;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;

use App\Form\InvoiceItemsFormType;
use App\Form\InvoiceFormType;

class InvoicesController extends AbstractController
{
    /**
     * @Route("/invoices", name="invoices")
     */
    #[Route('/invoices', name: 'invoices')]
    public function index(): Response
    {
        $user = $this->getUser();
        $cases = $user->getStaff()->getCases();

        $invoices = $this->getDoctrine()->getRepository(Invoice::class)->findByCases($cases);

        return $this->render('invoices/index.html.twig', [
            'invoices' => $invoices
        ]);
    }
    /**
     * @Route("/invoice/new", name="invoiceNew")
     */
    #[Route('/invoice/new', name: 'invoiceNew')]
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        $entityManager = $this->getDoctrine()->getManager();
        $invoice = new Invoice();
        $form = $this->createForm(InvoiceFormType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $event = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('invoices');
        }
        else
        {
            return $this->render('invoices/new.html.twig', [
                'invoice' => $invoice,
                'case_form' => $form->createView()
            ]);
        }
    }
    /**
     * @Route("/invoice/{id}", name="invoiceShow")
     */
    #[Route('/invoice/{id}', name: 'invoiceShow')]
    public function show(string $id): Response
    {
        $user = $this->getUser();
        $entityManager = $this->getDoctrine()->getManager();
        $invoice = $entityManager->getRepository(Invoice::class)->find($id);
        $invoiceitems = $entityManager->getRepository(InvoiceItems::class)->findByInvoiceID($invoice->getId());

        return $this->render('invoices/show.html.twig', [
            'invoice' => $invoice,
            'invoiceitems'=> $invoiceitems
        ]);
    }
    /**
     * @Route("/invoice/{id}/edit", name="invoiceEdit")
     */
    #[Route('/invoice/{id}/edit', name: 'invoiceEdit')]
    public function edit(string $id,Request $request): Response
    {
        $user = $this->getUser();
        $entityManager = $this->getDoctrine()->getManager();
        $invoice = $entityManager->getRepository(Invoice::class)->find($id);
        $form = $this->createForm(InvoiceFormType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $event = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('invoiceShow',array('id' => $id));
        }
        else
        {
            return $this->render('invoices/edit.html.twig', [
                'invoice' => $invoice,
                'case_form' => $form->createView()
            ]);
        }
    }
    /**
     * @Route("/invoice/{id}/print", name="invoicePrint")
     */
    #[Route('/invoice/{id}/print', name: 'invoicePrint')]
    public function print(string $id, Pdf $Pdf): Response
    {
        $user = $this->getUser();
        $entityManager = $this->getDoctrine()->getManager();
        $invoice = $entityManager->getRepository(Invoice::class)->find($id);
        $clientID = $invoice->getCases()->getClientID();
        $client = $entityManager->getRepository(Client::class)->findOneByID($clientID->getId());
        $invoiceitems = $entityManager->getRepository(InvoiceItems::class)->findByInvoiceID($invoice->getId());
        $html = $this->renderView('invoices/print.html.twig', [
            'invoice' => $invoice,
            'invoiceitems'=> $invoiceitems,
            'client'=> $client,
        ]);

        return new PdfResponse(
            $Pdf->getOutputFromHtml($html),
            'invoice.pdf'
        );
    }
    /**
     * @Route("/invoice/{invoiceid}/item/new", name="invoiceItemNew")
     */
    #[Route('/invoice/{invoiceid}/item/new', name: 'invoiceItemNew')]
    public function itemNew(string $invoiceid,Request $request): Response
    {
        $user = $this->getUser();
        $entityManager = $this->getDoctrine()->getManager();
        $invoice = $entityManager->getRepository(InvoiceItems::class)->find($invoiceid);
        $form = $this->createForm(InvoiceItemsFormType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $event = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('invoiceShow',array('id' => $invoiceid));
        }
        else
        {
            return $this->render('invoices/items/add.html.twig', [
                'invoice' => $invoice,
                'case_form' => $form->createView()
            ]);
        }
    }

    
    /**
     * @Route("/invoice/{invoiceid}/item/{id}/edit", name="invoiceItemEdit")
     */
    #[Route('/invoice/{invoiceid}/item/{id}/edit', name: 'invoiceItemEdit')]
    public function Itemedit(string $invoiceid,string $id,Request $request): Response
    {
        $user = $this->getUser();
        $entityManager = $this->getDoctrine()->getManager();
        $invoice = $entityManager->getRepository(InvoiceItems::class)->find($id);
        $form = $this->createForm(InvoiceItemsFormType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $event = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('invoiceShow',array('id' => $invoiceid));
        }
        else
        {
            return $this->render('invoices/items/edit.html.twig', [
                'invoice' => $invoice,
                'case_form' => $form->createView()
            ]);
        }
    }
    /**
     * @Route("/invoice/{invoiceid}/item/{id}/remove", name="invoiceItemRemove")
     */
    #[Route('/invoice/{invoiceid}/item/{id}/remove', name: 'invoiceItemRemove')]
    public function Itemremove(string $invoiceid,string $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $event = $entityManager->getRepository(Event::class)->find($id);
        $entityManager->remove($event);
        $entityManager->flush();

        return $this->redirectToRoute('invoiceShow',array('id' => $invoiceid));
    }
    /**
     * @Route("/invoice/{id}/remove", name="invoiceRemove")
     */
    #[Route('/invoice/{id}/remove', name: 'invoiceRemove')]
    public function remove(string $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $event = $entityManager->getRepository(Event::class)->find($id);
        $entityManager->remove($event);
        $entityManager->flush();

        return $this->redirectToRoute('dashboard');
    }
}

templates/invoices/edit.html.twig
{% extends 'logged.html.twig' %} {% block title %}Todo{% endblock %} {% block subtitle %}Todo{% endblock %} {% block
    body %}
    <h1>Edit Bellow</h1>
    <br>
    {{ form(case_form) }}
{% endblock %}

templates/invoices/index.html.twig
{% extends 'logged.html.twig' %} {% block title %}Invoices{% endblock %} {%
block subtitle %}Invoices{% endblock %} {% block body %}
  <div class="position-relative">
    <div class="float-right">
      <a href="{{ path('invoiceNew') }}" class="btn btn-primary">New</a>
    </div>
    <br /><br />
    {% if invoices %}
    <div class="position-relative">
      <i
        class="bi bi-info-circle float-right"
        data-bs-toggle="tooltip"
        title="    Green: Are Paid Invoices
    White: Is Upcoming Invoices
    Yellow: Is upaid and old invocies"
      ></i>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Date</th>
          <th scope="col">Paid</th>
        </tr>
      </thead>
      <tbody>
        {% for invoice in invoices %} {% if invoice.paid %}
        <tr class="table-success">
          {% elseif invoice.DateOfIssue < date() %}
        </tr>

        <tr class="table-warning">
          {% else %}
        </tr>

        <tr class="table-light">
          {% endif %}
          <td>
            <a href="{{ path('invoiceShow', { id: invoice.id }) }}">{{
              invoice.name
            }}</a>
          </td>
          <td>{{invoice.DateOfIssue|date("d/m/Y") }}</td>
          {% if invoice.paid %}
          <td>Yes</td>
          {% else %}
          <td>No</td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  {% endblock %}

templates/invoices/new.html.twig
{% extends 'logged.html.twig' %} {% block title %}Invoice{% endblock %} {% block
subtitle %}Invoice{% endblock %} {% block body %}
<h1>Add new Invoice:</h1>
<br />
{{ form(case_form) }}
{% endblock %}

templates/invoices/print.html.twig
{% extends 'print.html.twig' %} {% block title %}Invoice{% endblock %} {% block
subtitle %}Invoice{% endblock %} {% block body %}
<div class="container">
  <p>{{ "now" | date("d F Y", false) }}</p>
  <br />
  <br />

  <div>
    <p>{{ client.Fname }} {{ client.LName }}</p>
    <p>{{ client.Address }}</p>
  </div>
  <br />
  <div>
    <h3>Statement:</h3>
    <p>Dated: {{ invoice.dateOfIssue | date("d F Y", false) }}</p>
    <p>Solicitor: {{ invoice.BilledStaffID }}</p>
  </div>
  <br />
  <br />
  <h1>Case Items:</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Quantity</th>
        <th scope="col">Rate</th>
        <th scope="col">Adjustments</th>
      </tr>
    </thead>
    <tbody>
      {%for invoiceitem in invoiceitems %}
      <tr>
        <td>{{ invoiceitem.description }}</td>
        <td>{{ invoiceitem.quantity }}</td>
        <td>{{ invoiceitem.rate }}</td>
        <td>{{ invoiceitem.adjusments }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/invoices/show.html.twig
{% extends 'logged.html.twig' %} {% block title %}Invoice{% endblock %} {% block
subtitle %}Invoice{% endblock %} {% block body %}
<div class="position-relative">
  <div class="float-right">
    <a
    href="{{ path('invoicePrint', { id: invoice.id }) }}"
    class="btn btn-info"
    >Print</a
  >
    <a
      href="{{ path('invoiceEdit', { id: invoice.id }) }}"
      class="btn btn-warning"
      >Edit</a
    >
    <a
      href="{{ path('invoiceRemove', { id: invoice.id }) }}"
      class="btn btn-danger"
      >Remove</a
    >
  </div>
</div>
<h1>Name</h1>
<p>{{ invoice.name }}</p>

<h1>Date of Issue</h1>
<p>{{ invoice.dateOfIssue | date }}</p>

<h1>Paid</h1>
{%if invoice.paid %}
<p class="text-success"><i class="bi bi-check-circle"></i> Yes</p>
{%else %}
<p class="text-danger"><i class="bi bi-x"></i> No</p>
{%endif %}

<h1>Case Items:</h1>
<div class="position-relative">
  <div class="float-right">
    <a
      href="{{ path('invoiceItemNew', { invoiceid: invoice.id }) }}"
      class="btn btn-success"
      >New</a
    >
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Quantity</th>
      <th scope="col">Rate</th>
      <th scope="col">Adjustments</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {%for invoiceitem in invoiceitems %}
    <tr>
      <td>{{ invoiceitem.description }}</td>
      <td>{{ invoiceitem.quantity }}</td>
      <td>{{ invoiceitem.rate }}</td>
      <td>{{ invoiceitem.adjusments }}</td>
      <td>
        <a
          type="button"
          href="{{
            path('invoiceItemEdit', { invoiceid: invoice.id, id: invoiceitem.id })
          }}"
          >Edit</a
        >
      </td>
      <td>
        <a
          type="button"
          href="{{
            path('invoiceItemRemove', { invoiceid: invoice.id, id: invoiceitem.id })
          }}"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}