src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceRepository::class)
 */
class Invoice
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\ManyToOne(targetEntity=Staff::class, inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $BilledStaffID;

    /**
     * @ORM\Column(type="date")
     */
    private $DateOfIssue;

    /**
     * @ORM\OneToMany(targetEntity=InvoiceItems::class, mappedBy="InvoiceID", orphanRemoval=true)
     */
    private $invoiceItems;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Paid;

    /**
     * @ORM\ManyToOne(targetEntity=Cases::class, inversedBy="invoices")
     */
    private $cases;

    public function __toString(): string
    {
        return $this->Name;
    }

    public function __construct()
    {
        $this->invoiceItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getBilledStaffID(): ?Staff
    {
        return $this->BilledStaffID;
    }

    public function setBilledStaffID(?Staff $BilledStaffID): self
    {
        $this->BilledStaffID = $BilledStaffID;

        return $this;
    }

    public function getDateOfIssue(): ?\DateTimeInterface
    {
        return $this->DateOfIssue;
    }

    public function setDateOfIssue(\DateTimeInterface $DateOfIssue): self
    {
        $this->DateOfIssue = $DateOfIssue;

        return $this;
    }

    /**
     * @return Collection|InvoiceItems[]
     */
    public function getInvoiceItems(): Collection
    {
        return $this->invoiceItems;
    }

    public function addInvoiceItem(InvoiceItems $invoiceItem): self
    {
        if (!$this->invoiceItems->contains($invoiceItem)) {
            $this->invoiceItems[] = $invoiceItem;
            $invoiceItem->setInvoiceID($this);
        }

        return $this;
    }

    public function removeInvoiceItem(InvoiceItems $invoiceItem): self
    {
        if ($this->invoiceItems->removeElement($invoiceItem)) {
            // set the owning side to null (unless already changed)
            if ($invoiceItem->getInvoiceID() === $this) {
                $invoiceItem->setInvoiceID(null);
            }
        }

        return $this;
    }

    public function getPaid(): ?bool
    {
        return $this->Paid;
    }

    public function setPaid(bool $Paid): self
    {
        $this->Paid = $Paid;

        return $this;
    }

    public function getCases(): ?Cases
    {
        return $this->cases;
    }

    public function setCases(?Cases $cases): self
    {
        $this->cases = $cases;

        return $this;
    }
}

src/Entity/Staff.php
<?php

namespace App\Entity;

use App\Repository\StaffRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StaffRepository::class)
 */
class Staff
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Fname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Phone;


    /**
     * @ORM\OneToMany(targetEntity=Todo::class, mappedBy="CaseID", orphanRemoval=true)
     */
    private $todos;

    /**
     * @ORM\ManyToMany(targetEntity=Cases::class, mappedBy="Staff")
     */
    private $cases;

    /**
     * @ORM\OneToMany(targetEntity=Invoice::class, mappedBy="BilledStaffID", orphanRemoval=true)
     */
    private $invoices;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="staff", cascade={"persist", "remove"})
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Template::class, mappedBy="staff")
     */
    private $templates;

    public function __toString(): string
    {
        return $this->Fname. ' ' .$this->Lname;
    }

    public function __construct()
    {
        $this->todos = new ArrayCollection();
        $this->cases = new ArrayCollection();
        $this->invoices = new ArrayCollection();
        $this->caseTypes = new ArrayCollection();
        $this->templates = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFname(): ?string
    {
        return $this->Fname;
    }

    public function setFname(string $Fname): self
    {
        $this->Fname = $Fname;

        return $this;
    }

    public function getLname(): ?string
    {
        return $this->Lname;
    }

    public function setLname(string $Lname): self
    {
        $this->Lname = $Lname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    /**
     * @return Collection|Todo[]
     */
    public function getTodos(): Collection
    {
        return $this->todos;
    }

    public function addTodo(Todo $todo): self
    {
        if (!$this->todos->contains($todo)) {
            $this->todos[] = $todo;
        }

        return $this;
    }

    public function removeTodo(Todo $todo): self
    {
        if ($this->todos->removeElement($todo)) {
            // set the owning side to null (unless already changed)
            $todo->removeTodo($this);
        }

        return $this;
    }

    /**
     * @return Collection|Cases[]
     */
    public function getCases(): Collection
    {
        return $this->cases;
    }

    public function addCase(Cases $case): self
    {
        if (!$this->cases->contains($case)) {
            $this->cases[] = $case;
            $case->addStaff($this);
        }

        return $this;
    }

    public function removeCase(Cases $case): self
    {
        if ($this->cases->removeElement($case)) {
            $case->removeStaff($this);
        }

        return $this;
    }

    /**
     * @return Collection|Invoice[]
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices[] = $invoice;
            $invoice->setBilledStaffID($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getBilledStaffID() === $this) {
                $invoice->setBilledStaffID(null);
            }
        }

        return $this;
    }


    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Template[]
     */
    public function getTemplate(): Collection
    {
        return $this->templates;
    }

    public function addTemplate(Template $template): self
    {
        if (!$this->template->contains($template)) {
            $this->template[] = $template;
            $template->setStaff($this);
        }

        return $this;
    }

    public function removeTemplate(Template $template): self
    {
        if ($this->template->removeElement($template)) {
            // set the owning side to null (unless already changed)
            if ($template->getStaff() === $this) {
                $template->setStaff(null);
            }
        }

        return $this;
    }
}

src/Entity/Template.php
<?php

namespace App\Entity;

use App\Repository\TemplateRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TemplateRepository::class)
 */
class Template
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $File;

    /**
     * @ORM\ManyToOne(targetEntity=Staff::class, inversedBy="templates")
     */
    private $staff;

    /**
     * @ORM\Column(type="boolean")
     */
    private $global;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->File;
    }

    public function setFile(string $File): self
    {
        $this->File = $File;

        return $this;
    }

    public function getStaff(): ?Staff
    {
        return $this->staff;
    }

    public function setStaff(?Staff $staff): self
    {
        $this->staff = $staff;

        return $this;
    }

    public function getGlobal(): ?bool
    {
        return $this->global;
    }

    public function setGlobal(bool $global): self
    {
        $this->global = $global;

        return $this;
    }
}

src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TodoRepository::class)
 */
class Todo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;


    /**
     * @ORM\Column(type="datetime")
     */
    private $StartDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DueDate;

    /**
     * @ORM\ManyToOne(targetEntity=Cases::class, inversedBy="todos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $CaseID;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $note;

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }


    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->StartDate;
    }

    public function setStartDate(\DateTimeInterface $StartDate): self
    {
        $this->StartDate = $StartDate;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->DueDate;
    }

    public function setDueDate(\DateTimeInterface $DueDate): self
    {
        $this->DueDate = $DueDate;

        return $this;
    }

    public function getCaseID(): ?Cases
    {
        return $this->CaseID;
    }

    public function setCaseID(?Cases $CaseID): self
    {
        $this->CaseID = $CaseID;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\Entity\Cases;
use App\Entity\Event;
use App\Entity\Invoice;
use App\Entity\Staff;
use App\Entity\Client;
use App\Entity\CaseItems;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class SearchController extends AbstractController
{
    /**
     * @Route("/search", name="search")
     */
    #[Route('/search', name: 'search')]
    public function index(Request $request): Response
    {
        $search=$request->query->get('search');
        
        # Cases
        $cases = $this->getDoctrine()
        ->getRepository(Cases::class)
        ->findAny($search);
        
        # Case Items
        $caseitems = $this->getDoctrine()
        ->getRepository(CaseItems::class)
        ->findAny($search);

        # Events
        $events = $this->getDoctrine()
        ->getRepository(Event::class)
        ->findAny($search);
        
        # Invoices
        $invoices = $this->getDoctrine()
        ->getRepository(Invoice::class)
        ->findAny($search);
        
        # Staff
        $staff= $this->getDoctrine()
        ->getRepository(Staff::class)
        ->findAny($search);
        
        # Clients
        $clients = $this->getDoctrine()
        ->getRepository(Client::class)
        ->findAny($search);


        return $this->render('search/index.html.twig', [
            'search' => $search,
            'cases' => $cases,
            'caseitems' => $caseitems,
            'events' => $events,
            'invoices' => $invoices,
            'staffs' => $staff,
            'clients' => $clients,
        ]);
    }
}

templates/search/index.html.twig
{% extends 'logged.html.twig' %} {% block title %}Search{% endblock %} {% block
subtitle %}Search{% endblock %} {% block body %} {% if cases %}
<h1 class="border-bottom">Cases</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Client</th>
      <th scope="col">Staff</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for case in cases %}
    <tr>
      <td><a href="{{ path('case', {id: case.hashedId}) }}">{{case.name}}</a></td>
      <td><a href="{{ path('client', {caseid: case.ClientID}) }}">{{case.ClientID}}</a></td>
      <td><ul>
        {% for staff in case.Staff %}
        <li><a href="{{ path('staff', {id: staff.id}) }}">{{staff.fname}} {{staff.lname}} </a></li>
        {% endfor %}
      </ul></td>
      <td><a href="{{ path('editcase', {id: case.hashedId}) }}">Edit</a></td>
      <td><a href="{{ path('removecase', {id: case.hashedId}) }}">Delete</a></td>
    </tr>
  </a>
    {% endfor %}
  </tbody>
</table>

{% endif %} 

{% if caseitems %}
<h1 class="border-bottom">Cases</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">File</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {%for caseitem in caseitems %}
    <tr>
      <td>{{ caseitem.name }}</td>
      <td>{{ caseitem.file }}</td>
      <td>
        <a type="button" href="{{ path('editcase', { id: case.hashedId }) }}"
          >Edit</a
        >
      </td>
      <td>
        <a type="button" href="{{ path('removecase', { id: case.hashedId }) }}"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endif %} 

{% if events %}
<h1 class="border-bottom">Events</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {%for event in events %}
    <tr>
      <td>{{ event.name }}</td>
      <td>{{ caseitem.file }}</td>
      <td>
        <a type="button" href="{{ path('editevent', { id: event.id }) }}"
          >Edit</a
        >
      </td>
      <td>
        <a type="button" href="{{ path('removeevent', { id: event.id }) }}"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endif %} {% if invoices %}
<h1 class="border-bottom">Invoices</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date</th>
      <th scope="col">Case</th>
      <th scope="col">Paid</th>
    </tr>
  </thead>
  <tbody>
    {% for invoice in invoices %} {% if invoice.paid %}
    <tr class="table-success">
      {% elseif invoice.DateOfIssue < date() %}
    </tr>

    <tr class="table-warning">
      {% else %}
    </tr>

    <tr class="table-light">
      {% endif %}
      <td><a href="{{path('invoiceadd')}}">{{ invoice.name }}</a></td>
      <td>{{invoice.DateOfIssue|date("d/m/Y") }}</td>
      <td><a href="http://">{{invoice.cases }}</a></td>
      {% if invoice.paid %}
      <td>Yes</td>
      {% else %}
      <td>No</td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %} {% if staffs %}
<h1 class="border-bottom">Staff</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {%for staff in staffs %}
    <tr>
      <td>{{ staff.Fname }} {{staff.Lname}}</td>
      <td>
        <a type="button" href="{{ path('editstaff', { id: staff.id }) }}"
          >Edit</a
        >
      </td>
      <td>
        <a type="button" href="{{ path('removestaff', { id: staff.id }) }}"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %} {% if clients %}
<h1 class="border-bottom">Clients</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {%for event in events %}
    <tr>
      <td>{{ event.name }}</td>
      <td>{{ caseitem.file }}</td>
      <td>
        <a type="button" href="{{ path('editevent', { id: event.id }) }}"
          >Edit</a
        >
      </td>
      <td>
        <a type="button" href="{{ path('removeevent', { id: event.id }) }}"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %} {% endblock %}