src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TodoRepository::class)
 */
class Todo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;


    /**
     * @ORM\Column(type="datetime")
     */
    private $StartDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DueDate;

    /**
     * @ORM\ManyToOne(targetEntity=Cases::class, inversedBy="todos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $CaseID;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $note;

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }


    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->StartDate;
    }

    public function setStartDate(\DateTimeInterface $StartDate): self
    {
        $this->StartDate = $StartDate;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->DueDate;
    }

    public function setDueDate(\DateTimeInterface $DueDate): self
    {
        $this->DueDate = $DueDate;

        return $this;
    }

    public function getCaseID(): ?Cases
    {
        return $this->CaseID;
    }

    public function setCaseID(?Cases $CaseID): self
    {
        $this->CaseID = $CaseID;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

class DashboardController extends AbstractController
{
    /**
     * @Route("/dashboard", name="dashboard")
     */
    #[Route('/dashboard', name: 'dashboard')]
    public function index(Environment $twig): Response
    {
        $user = $this->getUser();

        $staff = $user->getStaff();

        $cases = $staff->getCases();

        return new Response($twig->render('dashboard/index.html.twig', [
            'controller_name' => 'DashboardController',
            'StaffName'=> $staff->getFname(),
            'cases'=> $cases,
            'todos'=> $staff->getTodos(),
            'invoices'=> $staff->getInvoices(),
            'current', getdate()
        ]));
    }
}

templates/dashboard/index.html.twig
{% extends 'logged.html.twig' %} {% block title %}Dashboard{% endblock %} {%
block subtitle %}Dashboard{% endblock %} {% block body %}
<div class="container">
  <h1>Hello {{ StaffName }}, Here are your upcoming events:</h1>
  <br />
  <div class="row">
    <div class="col border rounded">
      <h3 class="border-bottom">
        <i class="bi bi-calendar-event"></i> Upcoming Events
      </h3>
      {% for case in cases %} {% for event in case.events %}
      <a
        href="{{ path('eventShow', { id: event.id }) }}"
        class="list-group-item d-flex justify-content-between align-items-center"
      >
        <div class="container">
          <div class="row">
            <div class="col">
              <p>{{ event.name }}</p>
            </div>
            <div class="col">
              <p>{{ event.startDate | date }}</p>
            </div>
          </div>
        </div>
      </a>
      {% endfor %} {% endfor %}
    </div>
    <div class="col border rounded">
      <h3 class="border-bottom">
        <i class="bi bi-calendar2-event"></i> Upcoming Todo
      </h3>

      {% for todo in todos %}
      <a
        href="{{ path('todo', { id: todo.id }) }}"
        class="list-group-item d-flex justify-content-between align-items-center"
      >
        <div class="container">
          <div class="row">
            <div class="col">
              <p>{{ todo.name }}</p>
            </div>
            <div class="col">
              <span class="badge badge-pill badge-primary"
                >{{ date(todo.DueDate | date).diff(date()).days }} Days</span
              >
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
    <div class="col border rounded">
      <h3 class="border-bottom">
        <i class="bi bi-calendar4-event"></i> Unpaid Invoices
      </h3>

      {% for invoice in invoices %} {% if not invoice.Paid %}
      <a
        href="{{ path('invoiceShow', { id: invoice.id }) }}"
        class="list-group-item d-flex justify-content-between align-items-center"
      >
        <div class="container">
          <div class="row">
            <div class="col">
              <p>{{ invoice.name }}</p>
            </div>
            <div class="col">
              <span class="badge badge-pill badge-primary"
                >{{ date(invoice.DateOfIssue | date).diff(date()).days }} Days
                Difference</span>
            </div>
          </div>
        </div>
      </a>
      {% endif %} {% endfor %}
    </div>
  </div>
</div>
{% endblock %}